### ISSUE TITLE
底部出现广告

### ISSUE THREAD

**Issue by colorsakura** [Azero-NG/csdnRemoveAd#1]
![screenshot from 2018-06-09 08-58-38](https://user-images.githubusercontent.com/32534829/41191838-6410c1ec-6bc3-11e8-87da-576a4cca2717.png)

**Comment by logicr** [comment]
我的也是，正打算过来报告问题 =.=

**Comment by Azero-NG** [comment]
抱歉，最近考试周！
现在还有吗？
https://blog.csdn.net/jpc00939/article/details/79093371
我刚刚试了一下，没发现广告
![image](https://user-images.githubusercontent.com/21135073/41579995-c700c38c-73cb-11e8-85da-e7075973dfe9.png)

**Comment by Azero-NG** [comment]
如果还有，能把网页保存打包发一下吗？

**Comment by logicr** [comment]
https://blog.csdn.net/Logicr/article/details/80718257
![image](https://user-images.githubusercontent.com/32129547/41590668-23493674-73ea-11e8-9c0a-6e837236ca3a.png)

**Comment by colorsakura** [comment]
[1.tar.gz](https://github.com/Azero-NG/csdnRemoveAd/files/2115008/1.tar.gz)

**Comment by Azero-NG** [comment]
搞定啦（之前看不到广告，是因为开了abp）
