### ISSUE TITLE
CSDN检测当前广告样式的广告位需要满足宽和高均大于等于40

### ISSUE THREAD

**Issue by maxliu0221** [Azero-NG/csdnRemoveAd#2]
CSDN检测当前广告样式的广告位需要满足宽和高均大于等于40
![image](https://user-images.githubusercontent.com/29991268/44317525-62701e80-a464-11e8-906b-fc5c0bdf000b.png)

**Comment by Azero-NG** [comment]
本脚本需要配合abp类插件
请在此类软件中加入自定义规则，以解决csdn反去广告问题，否则会提示"CSDN检测当前广告样式的广告位需要满足宽和高均大于等于40"
自定义规则:https://static.mediav.com/js/mvf_news_feed.js
